name: flutter_image_conversion
description: >
  A lightweight Flutter plugin that enables conversion of HEIC images to JPEG or PNG format directly on iOS devices.
  Ideal for apps targeting image uploads, social sharing, or cross-platform compatibility.

version: 1.0.0
homepage: https://github.com/cyberprophet/flutter-image-conversion

environment:
  sdk: ^3.5.4
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.share.image.conversion.flutter_image_conversion
        pluginClass: FlutterImageConversionPlugin
      ios:
        pluginClass: FlutterImageConversionPlugin
